# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnXp4XLaUXRTJXsYYOh-jejfxt9D0w1t
"""

import streamlit as st
import pandas as pd

# Title of the app
st.title('Interactive Data Visualization App')

# Upload CSV
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded_file is not None:
    # Read the file into a DataFrame
    df = pd.read_csv(uploaded_file)
    st.write("Preview of the dataset:")
    st.write(df.head())

    # Let user select columns for visualization
    columns = df.columns.tolist()
    x_axis = st.selectbox('Select column for X-axis', columns)
    y_axis = st.selectbox('Select column for Y-axis', columns)

    # Generate a bar chart
    st.bar_chart(df[[x_axis, y_axis]].set_index(x_axis))
else:
    st.write("Please upload a CSV file to proceed.")